// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250401204434_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Irasas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Archyvuotas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("Dienos_pries")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Dienu_daznumas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Id_dok")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("Isigaliojimo_data")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Pabaigos_data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Pavadinimas")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Irasai");
                });

            modelBuilder.Entity("IrasasNaudotojas", b =>
                {
                    b.Property<int>("IrasasId")
                        .HasColumnType("int");

                    b.Property<string>("NaudotojasId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Prekes_Adminas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("IrasasId", "NaudotojasId");

                    b.HasIndex("NaudotojasId");

                    b.ToTable("IrasasNaudotojai");
                });

            modelBuilder.Entity("Naudotojas", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Adminas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("El_pastas")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Gimimo_data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Pareigos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Pavarde")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Vardas")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Naudotojai");
                });

            modelBuilder.Entity("IrasasNaudotojas", b =>
                {
                    b.HasOne("Irasas", "Irasas")
                        .WithMany("Naudotojai")
                        .HasForeignKey("IrasasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Naudotojas", "Naudotojas")
                        .WithMany("Irasai")
                        .HasForeignKey("NaudotojasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Irasas");

                    b.Navigation("Naudotojas");
                });

            modelBuilder.Entity("Irasas", b =>
                {
                    b.Navigation("Naudotojai");
                });

            modelBuilder.Entity("Naudotojas", b =>
                {
                    b.Navigation("Irasai");
                });
#pragma warning restore 612, 618
        }
    }
}
